name: environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - plotly
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - scikit-learn
